CREATE TABLE gender (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(1) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL UNIQUE,
    created_at NOT NULL TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by NOT NULL VARCHAR(255) DEFAULT 'system',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255)
);
