-- Insert admin UserLogin (password: MyAdminPassword, BCrypt hash with cost 12
-- generated by Quarkus BcryptUtil.bcryptHash)
INSERT INTO user_login (email, password, role, first_name, last_name, created_at, updated_at, active)
VALUES (
    'admin@example.com',
    '$2a$12$L5bdW0wku76BuKFp6vcc9.vGGq2P7mdRmi57fw6.Lgd5joN/wEtVW',
    'admin',
    'Admin',
    'User',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    TRUE
);
