-- Insert regular UserLogin (password: MyUserPassword, BCrypt hash with cost 12
-- generated by BcryptUtil.bcryptHash)
INSERT INTO user_login (email, password, role, first_name, last_name, created_at, updated_at, active)
VALUES (
    'user@example.com',
    '$2a$12$xjhK.E6v5uUtZLtIumknGeMG8ZRbQLYRUnauVZrVTNSz6HOXitora',
    'user',
    'Regular',
    'User',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    TRUE
)
ON CONFLICT (email) DO NOTHING;
